# Generated by Django 2.2.16 on 2022-09-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
